default: &default
  adapter: postgresql
  encoding: utf8
  collation: ja_JP.UTF-8
  ctype: ja_JP.UTF-8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  variables:
    statement_timeout: 60000

development:
  <<: *default
  database: webauthn_passkey_dev

test:
  <<: *default
  database: webauthn_passkey_tst

production:
  <<: *default
  database: webauthn_passkey_prd
